[tool.vulture]
# Указываем Vulture сканировать текущую директорию.
# Исключения будут применяться к этому пути.
paths = ["."]

# Список файлов и папок для исключения из анализа.
# Используются glob-паттерны.
exclude = [
    "backup_007/",                   # Исключаем папку backup_007 целиком
    ".backup-*/",                    # Исключаем все папки, имя которых начинается с .backup-
    "venv/",                         # Исключаем папку виртуального окружения venv
    "**/__pycache__/",               # Исключаем все папки __pycache__ на любом уровне вложенности
    ".git/",                         # Исключаем служебную папку .git
    "vulture_analysis.txt",          # Исключаем сам файл с результатами анализа (это файл, слеш не нужен)
    "src/qt-style-sheet-inspector/", # Предположительно сторонняя библиотека
    "src/qstyler/",                  # Предположительно сторонняя библиотека
]
min_confidence = 80 # Минимальный уровень уверенности (0-100)
# verbose = true                    # Установить в true для более детального вывода Vulture
